baseURL = 'https://dstorch.com/'
languageCode = 'en-us'
title = 'David Storch'

[[module.imports]]
path = "github.com/willfaught/paige"

[languages.en]
languagecode = "en-us"
languagedirection = "ltr"
languagename = "English"
title = "David Storch"
weight = 10

[languages.en.params.paige.site]
description = "Database Expert / Engineering Leader / Software Engineer"

[params.paige.pages]
disable_toc = true
disable_word_count = true
disable_reading_time = true

[params.paige.subpages]
disable_word_count = true
disable_reading_time = true

[params.paige.site]
disable_breadcrumbs = true
disable_credit = true
menu_style = "tabs"

# Allow raw HTML mixed with content.
[markup.goldmark.renderer]
unsafe = true

# TODO: Can this be moved to a separate CSS file?
[params.paige]
style = """
a {
    color: rgb(var(--bs-secondary-rgb));
}

#paige-site-credit {
    font-size: 14px;
}

.footer-icons {
    font-size: 20px;
    text-decoration: none;
    margin-right: 8px;
}

/* make active links at the top of the page black and others gray */
.nav-link .active {
    color: black;
}
.nav-link {
    color: rgb(var(--bs-secondary-rgb));
}
"""