baseURL = 'https://dstorch.com/'
languageCode = 'en-us'
title = 'David Storch'

[[module.imports]]
path = "github.com/willfaught/paige"

[languages.en]
languagecode = "en-us"
languagedirection = "ltr"
languagename = "English"
title = "David Storch"
weight = 10

[languages.en.params.paige.site]
description = "Database Expert / Engineering Leader / Software Engineer"

[params.paige.pages]
disable_toc = true
disable_word_count = true
disable_reading_time = true
disable_next = true
disable_prev = true

[params.paige.subpages]
disable_word_count = true
disable_reading_time = true
disable_summary = true

[params.paige.site]
menu_style = "tabs"
disable_breadcrumbs = true
disable_credit = true

# Allow raw HTML mixed with content.
[markup.goldmark.renderer]
unsafe = true